let animals = [
  {
    species: "cat",
    price: 100,
    gender: "female",
    weight: 3,
    breed: "persian",
    hair: "long",
    id: 1,
    birth_date: 1544047200000,
    is_sterile: true,
    image: "",
    color: "white"
  },
  {
    species: "cat",
    price: 150,
    gender: "male",
    weight: 0.5,
    breed: "persian",
    hair: "long",
    id: 2,
    birth_date: 1544047200000,
    is_sterile: false,
    image: "",
    color: "white"
  },
  {
    species: "cat",
    price: 120,
    gender: "female",
    weight: 2,
    breed: "persian",
    hair: "long",
    id: 3,
    birth_date: 1544047200000,
    is_sterile: true,
    image: "",
    color: "orange"
  },
  {
    species: "cat",
    price: 90,
    gender: "male",
    weight: 4,
    breed: "bobtail",
    hair: "medium",
    id: 4,
    birth_date: 1544047200000,
    is_sterile: true,
    image: "",
    color: "brown"
  },
  {
    species: "cat",
    price: 200,
    gender: "female",
    weight: 0.3,
    breed: "bobtail",
    hair: "long",
    id: 5,
    birth_date: 1576015200000,
    is_sterile: false,
    image: "",
    color: "brown"
  },
  {
    species: "cat",
    price: 200,
    gender: "male",
    weight: 0.25,
    breed: "bobtail",
    hair: "medium",
    id: 6,
    birth_date: 1576015200000,
    is_sterile: false,
    image: "",
    color: "orange"
  },
  {
    species: "cat",
    price: 300,
    gender: "male",
    weight: 3,
    breed: "british shorthair",
    hair: "short",
    id: 7,
    birth_date: 1425247200000,
    is_sterile: true,
    image: "",
    color: "gray"
  },
  {
    species: "cat",
    price: 350,
    gender: "female",
    weight: 3.5,
    breed: "british shorthair",
    hair: "short",
    id: 8,
    birth_date: 1444424400000,
    is_sterile: true,
    image: "",
    color: "gray"
  },
  {
    species: "cat",
    price: 600,
    gender: "female",
    weight: 0.3,
    breed: "british shorthair",
    hair: "short",
    id: 9,
    birth_date: 1575842400000,
    is_sterile: false,
    image: "",
    color: "gray"
  },
  {
    species: "cat",
    price: 600,
    gender: "male",
    weight: 0.3,
    breed: "british shorthair",
    hair: "short",
    id: 10,
    birth_date: 1575842400000,
    is_sterile: false,
    image: "",
    color: "gray"
  },
  {
    species: "dog",
    price: 800,
    gender: "female",
    weight: 3,
    breed: "labrador",
    croppedEars: 0,
    hair: "short",
    id: 11,
    birth_date: 1544047200000,
    is_sterile: true,
    image: "",
    color: "orange"
  },
  {
    species: "dog",
    price: 1000,
    gender: "male",
    weight: 2,
    breed: "labrador",
    croppedEars: 1,
    hair: "short",
    id: 12,
    birth_date: 1544047200000,
    is_sterile: false,
    image: "",
    color: "black"
  },
  {
    species: "dog",
    price: 1200,
    gender: "female",
    weight: 2,
    breed: "labrador",
    croppedEars: 1,
    hair: "short",
    id: 13,
    birth_date: 1544047200000,
    is_sterile: false,
    image: "",
    color: "brown"
  },
  {
    species: "dog",
    price: 600,
    gender: "male",
    weight: 25,
    breed: "siberian husky",
    croppedEars: 0,
    hair: "long",
    id: 14,
    birth_date: 1491426000000,
    is_sterile: false,
    image: "",
    color: "black-white"
  },
  {
    species: "dog",
    price: 1200,
    gender: "female",
    weight: 2,
    breed: "siberian husky",
    croppedEars: 0,
    hair: "long",
    id: 15,
    birth_date: 1544047200000,
    is_sterile: false,
    image: "",
    color: "black-white"
  },
  {
    species: "dog",
    price: 1000,
    gender: "male",
    weight: 2,
    breed: "siberian husky",
    croppedEars: 0,
    hair: "long",
    id: 16,
    birth_date: 1544047200000,
    is_sterile: false,
    image: "",
    color: "black-white"
  },
  {
    species: "dog",
    price: 1500,
    gender: "female",
    weight: 0.5,
    breed: "bulldog",
    croppedEars: 0,
    hair: "short",
    id: 17,
    birth_date: 1575928800000,
    is_sterile: false,
    image: "",
    color: "white-brown"
  },
  {
    species: "dog",
    price: 500,
    gender: "male",
    weight: 20,
    breed: "bulldog",
    croppedEars: 0,
    hair: "short",
    id: 18,
    birth_date: 1293832800000,
    is_sterile: true,
    image: "",
    color: "white-brown"
  },
  {
    species: "dog",
    price: 800,
    gender: "male",
    weight: 0.4,
    breed: "chihuahua",
    croppedEars: 0,
    hair: "short",
    id: 19,
    birth_date: 1575583200000,
    is_sterile: false,
    image: "",
    color: "brown"
  },
  {
    species: "dog",
    price: 1000,
    gender: "female",
    weight: 0.3,
    breed: "chihuahua",
    croppedEars: 0,
    hair: "short",
    id: 20,
    birth_date: 1544047200000,
    is_sterile: true,
    image: "",
    color: "orange"
  },
  {
    species: "fish",
    price: 100,
    gender: "female",
    weight: 0.01,
    breed: "clown loach",
    temper: "peacefull",
    maxSize: 2,
    id: 21,
    birth_date: 1554930000000,
    is_sterile: false,
    water_type: "limnetic",
    image: "",
    color: "orange-black"
  },
  {
    species: "fish",
    price: 100,
    gender: "male",
    weight: 0.01,
    breed: "clown loach",
    temper: "peacefull",
    maxSize: 2,
    id: 22,
    birth_date: 1554930000000,
    is_sterile: false,
    water_type: "limnetic",
    image: "",
    color: "orange-black"
  },
  {
    species: "fish",
    price: 100,
    gender: "male",
    weight: 0.01,
    breed: "clown loach",
    temper: "peacefull",
    maxSize: 2,
    id: 23,
    birth_date: 1554930000000,
    is_sterile: false,
    water_type: "limnetic",
    image: "",
    color: "orange-black"
  },
  {
    species: "fish",
    price: 60,
    gender: "male",
    weight: 0.01,
    breed: "red rasbora",
    temper: "peacefull",
    maxSize: 3,
    id: 24,
    birth_date: 1554843600000,
    is_sterile: false,
    water_type: "limnetic",
    image: "",
    color: "red"
  },
  {
    species: "fish",
    price: 60,
    gender: "male",
    weight: 0.01,
    breed: "red rasbora",
    temper: "peacefull",
    maxSize: 3,
    id: 25,
    birth_date: 1554843600000,
    is_sterile: false,
    water_type: "limnetic",
    image: "",
    color: "red-black"
  },
  {
    species: "fish",
    price: 60,
    gender: "female",
    weight: 0.01,
    breed: "red rasbora",
    temper: "peacefull",
    maxSize: 3,
    id: 26,
    birth_date: 1554843600000,
    is_sterile: false,
    water_type: "limnetic",
    image: "",
    color: "red"
  },
  {
    species: "fish",
    price: 300,
    gender: "female",
    weight: 0.03,
    breed: "oearl gourami",
    temper: "peacefull",
    maxSize: 5,
    id: 27,
    birth_date: 1576015200000,
    is_sterile: false,
    water_type: "limnetic",
    image: "",
    color: "white"
  },
  {
    species: "fish",
    price: 300,
    gender: "female",
    weight: 0.03,
    breed: "oearl gourami",
    temper: "peacefull",
    maxSize: 5,
    id: 28,
    birth_date: 1576015200000,
    is_sterile: false,
    water_type: "limnetic",
    image: "",
    color: "white-red"
  },
  {
    species: "fish",
    price: 300,
    gender: "male",
    weight: 0.03,
    breed: "oearl gourami",
    temper: "peacefull",
    maxSize: 5,
    id: 29,
    birth_date: 1576015200000,
    is_sterile: false,
    water_type: "limnetic",
    image: "",
    color: "white-red"
  },
  {
    species: "fish",
    price: 300,
    gender: "male",
    weight: 0.03,
    breed: "oearl gourami",
    temper: "peacefull",
    maxSize: 5,
    id: 30,
    birth_date: 1576015200000,
    is_sterile: false,
    water_type: "limnetic",
    image: "",
    color: "white"
  },
  {
    species: "bird",
    price: 2000,
    gender: "female",
    weight: 0.1,
    type: "parrot",
    breed: "amazon",
    id: 31,
    birth_date: 1544047200000,
    is_sterile: false,
    activity: "day",
    image: "",
    color: "green"
  },
  {
    species: "bird",
    price: 1000,
    gender: "male",
    weight: 0.25,
    type: "parrot",
    breed: "amazon",
    id: 32,
    birth_date: 1539118800000,
    is_sterile: false,
    activity: "day",
    image: "",
    color: "green"
  },
  {
    species: "bird",
    price: 4000,
    gender: "male",
    weight: 0.4,
    type: "parrot",
    breed: "african gray",
    id: 33,
    birth_date: 1544047200000,
    is_sterile: false,
    activity: "day",
    image: "",
    color: "gray-red"
  },
  {
    species: "bird",
    price: 200,
    gender: "female",
    weight: 0.1,
    type: "singing",
    breed: "canary",
    id: 34,
    birth_date: 1544047200000,
    is_sterile: false,
    activity: "day",
    image: "",
    color: "yellow"
  },
  {
    species: "bird",
    price: 300,
    gender: "male",
    weight: 0.1,
    type: "singing",
    breed: "canary",
    id: 35,
    birth_date: 1544047200000,
    is_sterile: false,
    activity: "day",
    image: "",
    color: "red"
  },
  {
    species: "bird",
    price: 300,
    gender: "female",
    weight: 0.1,
    type: "singing",
    breed: "canary",
    id: 36,
    birth_date: 1570654800000,
    is_sterile: false,
    activity: "day",
    image: "",
    color: "yellow-black"
  },
  {
    species: "bird",
    price: 500,
    gender: "female",
    weight: 0.15,
    type: "dove",
    breed: "diamond",
    id: 37,
    birth_date: 1570741200000,
    is_sterile: false,
    activity: "day",
    image: "",
    color: "gray"
  },
  {
    species: "bird",
    price: 510,
    gender: "male",
    weight: 0.15,
    type: "dove",
    breed: "diamond",
    id: 38,
    birth_date: 1572732000000,
    is_sterile: false,
    activity: "day",
    image: "",
    color: "gray"
  },
  {
    species: "bird",
    price: 620,
    gender: "female",
    weight: 0.15,
    type: "dove",
    breed: "ring-necked",
    id: 39,
    birth_date: 1554584400000,
    is_sterile: false,
    activity: "day",
    image: "",
    color: "gray"
  },
  {
    species: "bird",
    price: 650,
    gender: "female",
    weight: 0.15,
    type: "dove",
    breed: "ring-necked",
    id: 40,
    birth_date: 1554584400000,
    is_sterile: false,
    activity: "day",
    image: "",
    color: "gray"
  }
];

console.log(JSON.stringify(animals));
