const cats = [
  {
    species: 'cat',
    price: 100,
    gender: 'f',
    weight: 3,
    birthDate: '12-06-2018',
    size: 'average',
    note: '',
    breed: 'persian',
    sterile: 1,
    hair: 'long',
  },
  {
    species: 'cat',
    price: 150,
    gender: 'm',
    weight: 0.5,
    birthDate: '15-10-2019',
    size: 'average',
    note: '',
    breed: 'persian',
    sterile: 0,
    hair: 'long',
  },
  {
    species: 'cat',
    price: 120,
    gender: 'f',
    weight: 2,
    birthDate: '30-10-2018',
    size: 'average',
    note: '',
    breed: 'persian',
    sterile: 1,
    hair: 'long',
  },
  {
    species: 'cat',
    price: 90,
    gender: 'm',
    weight: 4,
    birthDate: '13-08-2017',
    size: 'average',
    note: '',
    breed: 'bobtail',
    sterile: 1,
    hair: 'medium',
  },
  {
    species: 'cat',
    price: 200,
    gender: 'f',
    weight: 0.3,
    birthDate: '12-11-2019',
    size: 'average',
    note: '',
    breed: 'bobtail',
    sterile: 0,
    hair: 'medium',
  },
  {
    species: 'cat',
    price: 200,
    gender: 'm',
    weight: 0.25,
    birthDate: '12-11-2019',
    size: 'average',
    note: '',
    breed: 'bobtail',
    sterile: 0,
    hair: 'medium',
  },
  {
    species: 'cat',
    price: 300,
    gender: 'm',
    weight: 3,
    birthDate: '03-02-2015',
    size: 'average',
    note: '',
    breed: 'british shorthair',
    sterile: 1,
    hair: 'short',
  },
  {
    species: 'cat',
    price: 350,
    gender: 'f',
    weight: 3.5,
    birthDate: '10-10-2015',
    size: 'average',
    note: '',
    breed: 'british shorthair',
    sterile: 1,
    hair: 'short',
  },
  {
    species: 'cat',
    price: 600,
    gender: 'f',
    weight: 0.3,
    birthDate: '12-09-2019',
    size: 'average',
    note: '',
    breed: 'british shorthair',
    sterile: 0,
    hair: 'short',
  },
  {
    species: 'cat',
    price: 600,
    gender: 'm',
    weight: 0.3,
    birthDate: '12-09-2019',
    size: 'average',
    note: '',
    breed: 'british shorthair',
    sterile: 0,
    hair: 'short',
  },
]

const dogs = [
  {
    species: 'dog',
    price: 800,
    gender: 'f',
    weight: 3,
    birthDate: '20-07-2019',
    size: 'big',
    note: '',
    breed: 'labrador',
    croppedEars: 0,
    hair: 'short',
    sterile: 1
  },
  {
    species: 'dog',
    price: 1000,
    gender: 'm',
    weight: 2,
    birthDate: '20-10-2019',
    size: 'big',
    note: '',
    breed: 'labrador',
    croppedEars: 1,
    hair: 'short',
    sterile: 0
  },
  {
    species: 'dog',
    price: 1200,
    gender: 'f',
    weight: 2,
    birthDate: '20-10-2019',
    size: 'big',
    note: '',
    breed: 'labrador',
    croppedEars: 1,
    hair: 'short',
    sterile: 0
  },
  {
    species: 'dog',
    price: 600,
    gender: 'm',
    weight: 25,
    birthDate: '04-06-2017',
    size: 'big',
    note: '',
    breed: 'siberian husky',
    croppedEars: 0,
    hair: 'long',
    sterile: 0,
  },
  {
    species: 'dog',
    price: 1200,
    gender: 'f',
    weight: 2,
    birthDate: '13-11-2019',
    size: 'big',
    note: '',
    breed: 'siberian husky',
    croppedEars: 0,
    hair: 'long',
    sterile: 0,
  },
  {
    species: 'dog',
    price: 1000,
    gender: 'm',
    weight: 2,
    birthDate: '13-11-2019',
    size: 'big',
    note: '',
    breed: 'siberian husky',
    croppedEars: 0,
    hair: 'long',
    sterile: 0
  },
  {
    species: 'dog',
    price: 1500,
    gender: 'f',
    weight: 0.5,
    birthDate: '12-10-2019',
    size: 'medium',
    note: '',
    breed: 'bulldog',
    croppedEars: 0,
    hair: 'short',
    sterile: 0,
  },
  {
    species: 'dog',
    price: 500,
    gender: 'm',
    weight: 20,
    birthDate: '01-01-2011',
    size: 'medium',
    note: '',
    breed: 'bulldog',
    croppedEars: 0,
    hair: 'short',
    sterile: 1
  },
  {
    species: 'dog',
    price: 800,
    gender: 'm',
    weight: 0.4,
    birthDate: '12-06-2019',
    size: 'small',
    note: '',
    breed: 'chihuahua',
    croppedEars: 0,
    hair: 'short',
    sterile: 0,
  },
  {
    species: 'dog',
    price: 1000,
    gender: 'f',
    weight: 0.3,
    birthDate: '15-06-2019',
    size: 'small',
    note: '',
    breed: 'chihuahua',
    croppedEars: 0,
    hair: 'short',
    sterile: 1,
  },
]

const birds = [
  {
    species: 'bird',
    price: 2000,
    gender: 'f',
    weight: 0.1,
    birthDate: '20-09-2019',
    size: 'medium',
    note: '',
    type: 'parrot',
    breed: 'amazon',
    activityTime: 'day'
  },
  {
    species: 'bird',
    price: 1000,
    gender: 'm',
    weight: 0.25,
    birthDate: '10-10-2018',
    size: 'medium',
    note: '',
    type: 'parrot',
    breed: 'amazon',
    activityTime: 'day'
  },
  {
    species: 'bird',
    price: 4000,
    gender: 'm',
    weight: 0.4,
    birthDate: '20-05-2019',
    size: 'medium',
    note: '',
    type: 'parrot',
    breed: 'african gray',
    activityTime: 'day'
  },
  {
    species: 'bird',
    price: 200,
    gender: 'f',
    weight: 0.1,
    birthDate: '20-09-2019',
    size: 'small',
    note: '',
    type: 'singing',
    breed: 'canary',
    activityTime: 'day'
  },
  {
    species: 'bird',
    price: 300,
    gender: 'm',
    weight: 0.1,
    birthDate: '20-10-2019',
    size: 'small',
    note: '',
    type: 'singing',
    breed: 'canary',
    activityTime: 'day'
  },
  {
    species: 'bird',
    price: 300,
    gender: 'f',
    weight: 0.1,
    birthDate: '10-10-2019',
    size: 'small',
    note: '',
    type: 'singing',
    breed: 'canary',
    activityTime: 'day'
  },
  {
    species: 'bird',
    price: 500,
    gender: 'f',
    weight: 0.15,
    birthDate: '10-11-2019',
    size: 'medium',
    note: '',
    type: 'dove',
    breed: 'diamond',
    activityTime: 'day'
  },
  {
    species: 'bird',
    price: 510,
    gender: 'm',
    weight: 0.15,
    birthDate: '11-03-2019',
    size: 'medium',
    note: '',
    type: 'dove',
    breed: 'diamond',
    activityTime: 'day'
  },
  {
    species: 'bird',
    price: 620,
    gender: 'f',
    weight: 0.15,
    birthDate: '04-07-2019',
    size: 'medium',
    note: '',
    type: 'dove',
    breed: 'ring-necked',
    activityTime: 'day'
  },
  {
    species: 'bird',
    price: 650,
    gender: 'f',
    weight: 0.15,
    birthDate: '04-07-2019',
    size: 'medium',
    note: '',
    type: 'dove',
    breed: 'ring-necked',
    activityTime: 'day'
  },
]

const fishes = [
  {
    species: 'fish',
    price: 100,
    gender: 'f',
    weight: 0.01,
    birthDate: '04-11-2019',
    size: 'small',
    note: '',
    type: 'limnetic',
    breed: 'clown loach',
    temper: 'peacefull',
    maxSize: 2,
  },
  {
    species: 'fish',
    price: 100,
    gender: 'm',
    weight: 0.01,
    birthDate: '04-11-2019',
    size: 'small',
    note: '',
    type: 'limnetic',
    breed: 'clown loach',
    temper: 'peacefull',
    maxSize: 2,
  },
  {
    species: 'fish',
    price: 100,
    gender: 'm',
    weight: 0.01,
    birthDate: '04-11-2019',
    size: 'small',
    note: '',
    type: 'limnetic',
    breed: 'clown loach',
    temper: 'peacefull',
    maxSize: 2,
  },
  {
    species: 'fish',
    price: 60,
    gender: 'm',
    weight: 0.01,
    birthDate: '04-10-2019',
    size: 'small',
    note: '',
    type: 'limnetic',
    breed: 'red rasbora',
    temper: 'peacefull',
    maxSize: 3,
  },
  {
    species: 'fish',
    price: 60,
    gender: 'm',
    weight: 0.01,
    birthDate: '04-10-2019',
    size: 'small',
    note: '',
    type: 'limnetic',
    breed: 'red rasbora',
    temper: 'peacefull',
    maxSize: 3,
  },
  {
    species: 'fish',
    price: 60,
    gender: 'f',
    weight: 0.01,
    birthDate: '04-10-2019',
    size: 'small',
    note: '',
    type: 'limnetic',
    breed: 'red rasbora',
    temper: 'peacefull',
    maxSize: 3,
  },
  {
    species: 'fish',
    price: 300,
    gender: 'f',
    weight: 0.03,
    birthDate: '12-11-2019',
    size: 'small',
    note: '',
    type: 'limnetic',
    breed: 'oearl gourami',
    temper: 'peacefull',
    maxSize: 5,
  },
  {
    species: 'fish',
    price: 300,
    gender: 'f',
    weight: 0.03,
    birthDate: '12-11-2019',
    size: 'small',
    note: '',
    type: 'limnetic',
    breed: 'oearl gourami',
    temper: 'peacefull',
    maxSize: 5,
  },
  {
    species: 'fish',
    price: 300,
    gender: 'm',
    weight: 0.03,
    birthDate: '12-11-2019',
    size: 'small',
    note: '',
    type: 'limnetic',
    breed: 'oearl gourami',
    temper: 'peacefull',
    maxSize: 5,
  },
  {
    species: 'fish',
    price: 300,
    gender: 'm',
    weight: 0.03,
    birthDate: '12-11-2019',
    size: 'small',
    note: '',
    type: 'limnetic',
    breed: 'oearl gourami',
    temper: 'peacefull',
    maxSize: 5,
  },
]

const animals = [...cats, ...dogs, ...fishes, ...birds]

console.log(animals)